USE TERC;

CREATE TABLE State_Of_The_Lake
(

	Report_Year int not null,
	Max_Air_Temp_Ave real null,	
	Min_Air_Temp_Ave real null,	
	Annual_Precipitation real null,	
	Annual_Snow real null,
	Snow_Propotion real null,
	Monthly_Max_Air_Temp_Jan real null,	
	Monthly_Max_Air_Temp_Feb real null,
	Monthly_Max_Air_Temp_Mar real null,
	Monthly_Max_Air_Temp_Apr real null,
	Monthly_Max_Air_Temp_May real null,
	Monthly_Max_Air_Temp_Jun real null,
	Monthly_Max_Air_Temp_July real null,	
	Monthly_Max_Air_Temp_Aug real null,	
	Monthly_Max_Air_Temp_Sep real null,	
	Monthly_Max_Air_Temp_Oct real null,
	Monthly_Max_Air_Temp_Nov real null,
	Monthly_Max_Air_Temp_Dec real null,
	Monthly_Min_Air_Temp_Jan real null,
	Monthly_Min_Air_Temp_Feb real null,
	Monthly_Min_Air_Temp_Mar real null,
	Monthly_Min_Air_Temp_Apr real null,
	Monthly_Min_Air_Temp_May real null,
	Monthly_Min_Air_Temp_Jun real null,
	Monthly_Min_Air_Temp_July real null,
	Monthly_Min_Air_Temp_Aug real null,
	Monthly_Min_Air_Temp_Sep real null,
	Monthly_Min_Air_Temp_Oct real null,
	Monthly_Min_Air_Temp_Nov real null,
	Monthly_Min_Air_Temp_Dec real null,
	Monthly_Precipitation_Jan real null,
	Monthly_Precipitation_Feb real null,
	Monthly_Precipitation_Mar real null,
	Monthly_Precipitation_Apr real null,
	Monthly_Precipitation_May real null,
	Monthly_Precipitation_Jun real null,
	Monthly_Precipitation_July real null,
	Monthly_Precipitation_Aug real null,
	Monthly_Precipitation_Sep real null,
	Monthly_Precipitation_Oct real null,
	Monthly_Precipitation_Nov real null,
	Monthly_Precipitation_Dec real null,
	Surface_Water_Temp_Ave real null,
	Secchi_Annual_Ave real null,
	Secchi_Winter_Ave real null,
	Secchi_Summer_Ave real null,
	Chla_Ave real null,
        primary key (Report_Year)

)

